const int  BLUE_STRAFE_TIME =350;
const int  BLUE_SKYRISE_BASE_ANGLE =500;
const int  BLUE_MUSTARD_FORWARD =-92;
const int  BLUE_LITTLE_ELEVATOR= 280;
const int  BLUE_FULL_HEIGHT_ELEVATOR =700;
const int  BLUE_FORWARD_TO_BASE =-125;
const int  BLUE_TIME_TO_BRING_DOWN_EL =1200;

const int  RED_STRAFE_TIME =320;
const int  RED_SKYRISE_BASE_ANGLE = 510;
const int  RED_MUSTARD_FORWARD =-95;
const int  RED_LITTLE_ELEVATOR= 180;
const int  RED_FULL_HEIGHT_ELEVATOR =700;
const int  RED_FORWARD_TO_BASE =-110;
const int  RED_TIME_TO_BRING_DOWN_EL =1200;
