const int  STRAFE_TIME =500;
const int  SKYRISE_BASE_ANGLE =-390;
const int  MUSTARD_FORWARD =-120;
const int  LITTLE_ELEVATOR = 200;
const int  FULL_HEIGHT_ELEVATOR =700;
const int  FORWARD_TO_BASE = 85;
const int  TIME_TO_BRING_DOWN_EL =1200;
const int  SECOND_FORWARD_TO_MUSTARD =-200;

//new
const int TO_DROP_MUSTARD = 4000;
const int EL_LITTLE_ELEVATOR = 400;
const int EL_SLIGHTLY_ABOVE_HOLDER = 775;
const int TO_MUSTARD_HOLDER = 1170;
const int EL_SECOND_HEIGHT = 650;
const int EL_BACK_OVER_2 = 1000;

const int TO_DROP_MUSTARD_TWO = 4150;
const int TO_DROP_SECOND_MUSTARD_TWO = 4400;
const int EL_LITTLE_ELEVATOR_TWO = 400;
const int EL_SLIGHTLY_ABOVE_HOLDER_TWO = 775;
const int TO_MUSTARD_HOLDER_TWO = 1170;
const int EL_SECOND_HEIGHT_TWO = 675;
const int EL_BACK_OVER_2_TWO = 1100;
